### ISSUE TITLE
 [Feature Request]

### ISSUE THREAD

**Issue by barzilouik** [nickgerace/gfold#10]
* in the table rows, one could have a **clickable repository url**
  * and of course a state against the local repo : **upgradable (5 commits)**

with colors, in term of importance (new version > commits > minor commit > ...)

my 2 cents, I wanted to build the same tool, and I'm surprised how compact the code is, bravo!

**Comment by nickgerace** [comment]
Thank you for the kind comments and suggestions. I'd be happy to implement as many as possible, and will take a look in my spare time.

**Comment by nickgerace** [comment]
Okay, so I'll address each request accordingly.

## 1. Clickable Repository URL in the Table Rows

On my machine, GNOME terminal on Fedora 32, I can click a URL with _CTRL + LEFT CLICK_. This opens up that URL with my default browser. For instance...

```
% gfold -p ~/
.oh-my-zsh           clean    master   https://github.com/ohmyzsh/ohmyzsh.git 
```

Clicking on "https://github.com/ohmyzsh/ohmyzsh.git" brings me to [its corresponding URL](https://github.com/ohmyzsh/ohmyzsh). Perhaps this is a [terminal specific](https://unix.stackexchange.com/questions/284476/terminal-create-hyperlinks) issue?

## 2. Granularity in Repository Status

For this request, I'm looking for clarification. Would you like more granularity than just "clean" and "unclean"? Perhaps, this inclues a metric stating how many commits ahead/behind the current branch is.

The other way I perceived this is that **gfold** might want to check its local version versus the newest one on GitHub.

Am I on the right track here? Just want to make sure I am understanding correctly. Thank you.

**Comment by nickgerace** [comment]
Closing this for now since I believe ```gfold``` includes these features. Please feel free to comment if there's anything else that I can help with.
