### ISSUE TITLE
Arch Linux (AUR) Packages

### ISSUE THREAD

**Issue by orhun** [nickgerace/gfold#16]
Hi,
I came across your project and I liked it. It looks promising for sure. 🚀 
I'm also a Rust developer and I [maintain](https://github.com/orhun/PKGBUILDs) [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) packages in my spare time. So I created the following packages for the installation of `gfold` on Arch Linux and other distributions that support installing packages from [AUR](https://aur.archlinux.org/):

* [gfold](https://aur.archlinux.org/packages/gfold/) (builds from source)
* [gfold-git](https://aur.archlinux.org/packages/gfold-git/) (VCS/development package)

Installation can be made simply by a [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers) such as [yay](https://github.com/Jguer/yay). (e.g: `yay -S gfold`)

Feel free to update your documentation regarding to the AUR packages and installation. (I would propose a PR if requested)

Take care,
orhun.

**Comment by nickgerace** [comment]
Hi orhun,

Thank you for doing so! Glad to hear your thoughts, and I look forward to polishing the project further.

I'll _update my documentation accordingly and update this issue afterwards_. Please stay tuned. Thank you again for adding this to the AUR. It's folks like you who make the Arch Linux community great.

Nick

**Comment by nickgerace** [comment]
Finished this in the above PR. Thanks again!

**Comment by nickgerace** [comment]
I should let you know as well @orhun, this LICENSE for this project has changed to Apache 2.0 from MIT for release 0.3.1 and beyond. Please let me know if you would like me to file an issue, or make a PR, on your [repository](https://github.com/orhun/PKGBUILDs).

**Comment by orhun** [comment]
Both [gfold](https://github.com/orhun/PKGBUILDs/blob/master/gfold/PKGBUILD#L10) and [gfold-git](https://github.com/orhun/PKGBUILDs/blob/master/gfold-git/PKGBUILD#L10) packages are distributed under the MIT license. [PKGBUILDs](https://github.com/orhun/PKGBUILDs) is the maintenance repository where I push the [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD)s that I create/maintain. So the repository itself (the files that AUR needs) is licensed under GPLv3. I think no action is required in this case.

But of course feel free to submit a PR for your changes about the `gfold` packages.

**Comment by orhun** [comment]
I updated the LICENSE information of both [gfold](https://github.com/orhun/PKGBUILDs/blob/master/gfold/PKGBUILD#L10) and [gfold-git](https://github.com/orhun/PKGBUILDs/blob/master/gfold-git/PKGBUILD#L10) packages.

Feel free to submit a PR about the `gfold` packages if I couldn't catch an update.

**Comment by orhun** [comment]
PS: I can also create a `-bin` package (for installing the latest binary) if you upload a x86_64 binary along with a SHA checksum when you start creating releases via CI/CD workflow like [this](https://github.com/orhun/kmon/blob/master/.github/workflows/cd.yml#L30).

**Comment by nickgerace** [comment]
Thank you again. I will submit a PR if something changes!

I have to change the CI/CD pipeline for the repository anyway, so I appreciate the information. I'll definitely considering following that pattern when I take a look at changing the workflow.

**Comment by orhun** [comment]
Here's the `-bin` package: https://aur.archlinux.org/packages/gfold-bin/

**Comment by nickgerace** [comment]
Great to see. Thank you, @orhun.
