### ISSUE TITLE
How would TUI mode fit in this project?

### ISSUE THREAD

**Issue by Dentrax** [nickgerace/gfold#169]
Just thinking about how TUI mode would fit in this project. We can do some operations on the TUI as such: jump, delete, sync, fetch, copy path, rename, move, etc.

Wdyt?

**Comment by nickgerace** [comment]
I think [gitui](https://github.com/extrawurst/gitui) handles TUI integrations very well. `gfold` is designed to give a bird's eye view of your repositories on disk, and then exit. I could see a use case where a user sees a certain status for a given repository and then wants to operate on it (e.g. rename, move, jump), but I think that would be best handled by jumping to `gitui`.

Now, a potential idea is an integration with `gitui`. For example, a minimal TUI layer could be added to `gfold` that then jumps to `gitui`.

Thoughts on that idea?

**Comment by Dentrax** [comment]
> I think gitui handles TUI integrations very well and it would be redundant to have gfold do the same within an single repository.

Oh, I see now. Thanks.

> a minimal TUI layer could be added to gfold that then jumps to gitui

Sounds cool idea!

**Comment by nickgerace** [comment]
Seems like maybe https://github.com/nickgerace/gfold/issues/168 and this issue could combine into something like the following:

- Add an optional interactive mode
- The interactive mode should feel like a traditional TUI with the ability to jump to a highlighted repository in the results
- The jump should be able to `cd` at minimum, but there might also be an option to drop right into `gitui` as well

What do you think? :)

**Comment by Dentrax** [comment]
I would definitely use the interactive mode. :) I think interacting with `gfold` would provide much better UX in long-term.

Currently, It only shows the git projects and works like a charm. But we can iterate this project further:

* `cd`ing
* rename/move/etc.
* copy `pwd` or upstream url
* filter by `clean` status
* filter by project name
* filter by programming language
* stash and backup all working state
* sync all to upsteam
* ... _you name it_
