### ISSUE TITLE
Json output

### ISSUE THREAD

**Issue by AckslD** [nickgerace/gfold#176]
Really great project! :)

What do you think about having an option to output as json. This would make it easy/ier to integrate with other tools/scripts.

**Comment by AckslD** [comment]
Great! :)

Btw, I was playing around with making an `neovim` plugin based on `gfold`. It's currently WIP but was curious if you have some thoughts about it.

https://github.com/AckslD/nvim-gfold.lua

Currently I just wrote a very simple python script to parse the output of `gfold` to `json` but would remove that if we can directly get `json`.

**Comment by nickgerace** [comment]
@AckslD I missed your edits until I came back just now! What a great project! I'll open another issue to include your project in the README. Thank you very much for sharing both projects to others.
