### ISSUE TITLE
Investigate adding ability to grab and display submodule information

### ISSUE THREAD

**Issue by ranebrown** [nickgerace/gfold#177]
It would be nice to also so info on any submodules of a project. I haven't used subtrees but that might be another feature. Cool project!

**Comment by nickgerace** [comment]
That would be interesting! I'll investigate and see if we can do it.

**Comment by nickgerace** [comment]
#221 adds rudimentary support for submodules collection. We'll tackle displaying it in modes other than `json` in another issue.
