### ISSUE TITLE
`Error: StdIo(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

### ISSUE THREAD

**Issue by nickgerace** [nickgerace/gfold#190]
With `gfold 4.0.0-rc.1`, executing the binary results in the following error:
```
Error: StdIo(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```
However, if the `-i` flag is passed in, then it works. I suspect the issue is related to #181.

Original comment: https://github.com/nickgerace/gfold/issues/187#issuecomment-1066765249

**Comment by nickgerace** [comment]
Found the bug: it fails if ~/.config/gfold.toml (or Windows equivalent) does not exist. Current workaround: create an empty file at that location with that name.

**Comment by AckslD** [comment]
@nickgerace I can confirm that creating an empty config file works.

However I got another error, see #192
