### ISSUE TITLE
Error when remote is not 'origin'

### ISSUE THREAD

**Issue by AckslD** [nickgerace/gfold#192]
When the upstream of a branch I get the error:
```
Error: Git2Rs(Error { code: -3, klass: 4, message: "no reference found for shorthand 'origin/<branch-name>'" })
```
In this case the upstream is called 'fork' of the given branch.

**Comment by nickgerace** [comment]
I'll take a look at this soon. The short reason why this is likely happening: there's some hardcoded logic to look for `origin/<branch-name>` for the unpushed check if I recall correctly. I've been a bit busy, but will take a look soon.

**Comment by nickgerace** [comment]
I should mention too, I'll try to add your scenario here as an integration test!
