### ISSUE TITLE
Allow `$HOME` and `~` in config

### ISSUE THREAD

**Issue by nickgerace** [nickgerace/gfold#255]

**Comment by uncenter** [comment]
Looking around online it seems that there are some complicated uses of the tilde that would be difficult to expand (https://www.gnu.org/software/libc/manual/html_node/Tilde-Expansion.html),  and there aren't any great crates for this (https://blog.liw.fi/posts/2021/10/12/tilde-expansion-crates/ is a bit old but still accurate) right now. Might just be good to use a naive approach of replacing a starting `~/` or `$HOME` (just this one string, not arbitrary environment variables) with the current users home directory.

**Comment by nickgerace** [comment]
Fair points! If you'd like to take a look, that would be awesome and I'd be grateful. No pressure though. I'll mark the issue accordingly.
