### ISSUE TITLE
Investigate switching to `kdl` or `lua` for the config language

### ISSUE THREAD

**Issue by nickgerace** [nickgerace/gfold#256]

**Comment by uncenter** [comment]
I'd probably skip this one. I don't see any advantages by overcomplicating the config languages, especially as I don't see what kind of dynamic nature the configuration would ever require - this would only bloat the binary size and make it harder to use imo.

**Comment by nickgerace** [comment]
Sounds good! It was more of a passing thought and I don't remember the original context fully.

**Comment by nickgerace** [comment]
Closing for now since I agree!
