### ISSUE TITLE
way to specify multiple directories via config?

### ISSUE THREAD

**Issue by zachvalenta** [nickgerace/gfold#261]
Based on the README, seems like - whether from shell or config - only able to specify single path:

> By default, gfold looks at every Git repository via traversal from the current working directory. If you would like to target another directory, you can pass its path (relative or absolute) as the first argument or change the default path in the config file.

```toml
path = '/home/neloth'
```

My first thought on discovering this repo (h/t https://terminaltrove.com/) is it would be great for:

* specifying a list of repos I'm working with daily, especially those that exist on multiple machines and for which I want to avoid merge hell
* run gfold before leaving for/from the office and see "do I need to commit anything?"

Anyhow, keep up the good work and great project!

**Comment by nickgerace** [comment]
This is a good idea! Yes, it only looks at one path now, but I think allowing for multiple paths is a good idea. I'll mark it as "seeking contribution" for now, but may tackle it myself.

And thank you for telling me where you found `gfold` from! It helps a lot.

**Comment by SoutrikBandyopadhyay** [comment]
@nickgerace I would be happy to work on this. I believe we should modify both the CLI and the config file specification for the same.

I am thinking of the following usage for the cli - 

`gfold path1 path2 path3`,

and for the config file 

`paths = ["path1", "path2", "path3"]`.

I am not able to figure out a way to implement this functionality in a backwards compatible way. If you or @zachvalenta have any ideas let me know.

**Comment by nickgerace** [comment]
@SoutrikBandyopadhyay thank you! I'd have both the `path` and `paths` option in the config and return an error if the user provides both. It's not the most elegant solution, but I am planning a `5.0.0` release where we can drop the old `path` option depending on how this goes too.

**Comment by uncenter** [comment]
I think both could be supported in a backwards-compatible way. If `path` is supplied from config file, print a deprecation warning and then put the single path into a vec, like `paths` would be. (`path` and `paths` would be mutually exclusive, so an error in that scenario as well.) The CLI can start accepting multiple `[PATHS]...`, which is still backwards compatible with a single `[PATH]`. At a later date `path` support could be removed in a major update as mentioned earlier.
