### ISSUE TITLE
Ensure installation works for homebrew, Arch, nixpkgs, etc. now that crates have been consolidated

### ISSUE THREAD

**Issue by nickgerace** [nickgerace/gfold#274]
**EDIT: the first release containing these changes is `4.6.0`. Original issue description below...**

---

For the next release containing #271, we should check on commonly used upstream package management repositories to see that they reflect the changes.

- [Homebrew](https://github.com/Homebrew/homebrew-core/blob/d14372aa33297224e2738afea52e0d22150b40f3/Formula/g/gfold.rb)
- [nixpkgs](https://github.com/NixOS/nixpkgs/blob/33b9d57c656e65a9c88c5f34e4eb00b83e2b0ca9/pkgs/applications/version-management/gfold/default.nix)
- [Arch Linux](https://archlinux.org/packages/extra/x86_64/gfold/)

Note: we should not stress about tracking down every single `gfold` package in existence. Rather, this is more of a communal task to help package maintainers out where we can and within reason.

**Comment by uncenter** [comment]
Happy to take care of the Nixpkgs side of things btw.

**Comment by nickgerace** [comment]
@uncenter thank you! No pressure. Let's wait on next release. I'm thinking we could release `4.5.2` with just dependency bumps to test it.

**Comment by nickgerace** [comment]
It's worth noting this might require no changes either, depending on how `gfold` is packaged.

**Comment by nickgerace** [comment]
Okay, version `4.6.0` should contain changes that may affect `gfold` packages.

**Comment by orhun** [comment]
Updated the Arch package to `4.6.0` - all seems good :)

**Comment by nickgerace** [comment]
@orhun thank you! I looked at the nixpkgs and homebrew source code and both appear to be compatible with the change. Closing!
