### ISSUE TITLE
feature request: show unpushed commits or untracked branches

### ISSUE THREAD

**Issue by bbigras** [nickgerace/gfold#80]
I use a lot of repos for work and maybe it could be nice to know if I didn't push my changes.

**Comment by nickgerace** [comment]
I can take a look in my spare time. Sounds like a good idea.

**Comment by nickgerace** [comment]
Did some initial prototyping and I have an idea on how to determine what constitutes an "unpushed" commit.

**Comment by nickgerace** [comment]
Released in version 0.8.0

**Comment by nickgerace** [comment]
Reopening due to bug #92

**Comment by nickgerace** [comment]
Closing in favor of #92 since the discussion is there.
